//
//  FlightList.swift
//  InternshipApp
//
//  Created by Sead Mašetić on 3. 9. 2024..
//

import Foundation

struct FlightList {
    var flights: [FlightModel] = [
        FlightModel(town: "Mostar",
                    airportCode: "MST",
                    airportFullName: "Mostar International Airport",
                    possibleAirports: ["MUC", "IST"]),
        
        FlightModel(town: "Sarajevo",
                    airportCode: "SJJ",
                    airportFullName: "Sarajevo International Airport",
                    possibleAirports: ["LGA", "IST"]),
        
        FlightModel(town: "New York",
                    airportCode: "LGA",
                    airportFullName: "LaGuardia Airport",
                    possibleAirports: ["SJJ", "MST", "ZRH", "LOS", "FCO", "MUC"]),
        
        FlightModel(town: "Istanbul",
                    airportCode: "IST",
                    airportFullName: "Istanbul Airport",
                    possibleAirports: ["SJJ", "MST"]),
        
        FlightModel(town: "Munchen",
                    airportCode: "MUC",
                    airportFullName: "Munich International Airport",
                    possibleAirports: ["LGA", "IST", "SJJ", "MST"]),
        
        FlightModel(town: "Zurich",
                    airportCode: "ZRH",
                    airportFullName: "Zurich Airport",
                    possibleAirports: ["SJJ", "LGA", "MUC"]),
        
        FlightModel(town: "Lagos",
                    airportCode: "LOS",
                    airportFullName: "Murtala Muhammed International Airport",
                    possibleAirports: ["ZRH"]),
        
        FlightModel(town: "Rome",
                    airportCode: "FCO",
                    airportFullName: "Leonardo da Vinci–Fiumicino Airport",
                    possibleAirports: ["MUC", "LGA", "ZRH", "SJJ"])
    ]
    
    var flightOffers: [FlightOfferModel] = [
        FlightOfferModel(departureCode: "MST",
                         departureTown: "Mostar",
                         arrivalCode: "IST",
                         arrivalTown: "Istanbul",
                         flightDuration: "12:45",
                         time: "09:30 AM",
                         date: Date(),
                         airCompany: "Qatar Airways",
                         price: 250),
        
        FlightOfferModel(departureCode: "SJJ",
                         departureTown: "Sarajevo",
                         arrivalCode: "IST",
                         arrivalTown: "Istanbul",
                         flightDuration: "2:15",
                         time: "01:20 PM",
                         date: Date(),
                         airCompany: "Turkish Airlines",
                         price: 190),
        
        FlightOfferModel(departureCode: "MUC",
                         departureTown: "Munchen",
                         arrivalCode: "SJJ",
                         arrivalTown: "Sarajevo",
                         flightDuration: "1:50",
                         time: "10:00 AM",
                         date: Date(),
                         airCompany: "Lufthansa",
                         price: 220),
        
        FlightOfferModel(departureCode: "LGA",
                         departureTown: "New York",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "8:30",
                         time: "07:00 AM",
                         date: Date(),
                         airCompany: "Ryanair",
                         price: 350),
        
        FlightOfferModel(departureCode: "LGA",
                         departureTown: "New York",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "8:30",
                         time: "07:00 AM",
                         date: Date(),
                         airCompany: "Swiss Air",
                         price: 450),
        
        FlightOfferModel(departureCode: "FCO",
                         departureTown: "Rome",
                         arrivalCode: "LGA",
                         arrivalTown: "New York",
                         flightDuration: "9:15",
                         time: "11:00 AM",
                         date: Date(),
                         airCompany: "Alitalia",
                         price: 380),
        
        FlightOfferModel(departureCode: "MUC",
                         departureTown: "Munchen",
                         arrivalCode: "IST",
                         arrivalTown: "Istanbul",
                         flightDuration: "2:00",
                         time: "06:00 AM",
                         date: Date(),
                         airCompany: "Turkish Airlines",
                         price: 200),
        
        FlightOfferModel(departureCode: "MUC",
                         departureTown: "Munchen",
                         arrivalCode: "IST",
                         arrivalTown: "Istanbul",
                         flightDuration: "2:10",
                         time: "09:00 AM",
                         date: Date(),
                         airCompany: "Lufthansa",
                         price: 230),
        
        FlightOfferModel(departureCode: "ZRH",
                         departureTown: "Zurich",
                         arrivalCode: "SJJ",
                         arrivalTown: "Sarajevo",
                         flightDuration: "2:00",
                         time: "08:00 AM",
                         date: Date(),
                         airCompany: "Swiss Air",
                         price: 210),
        
        FlightOfferModel(departureCode: "ZRH",
                         departureTown: "Zurich",
                         arrivalCode: "LGA",
                         arrivalTown: "New York",
                         flightDuration: "8:45",
                         time: "05:00 AM",
                         date: Date(),
                         airCompany: "Swiss Air",
                         price: 400),
        
        FlightOfferModel(departureCode: "LGA",
                         departureTown: "New York",
                         arrivalCode: "FCO",
                         arrivalTown: "Rome",
                         flightDuration: "9:00",
                         time: "10:00 PM",
                         date: Date(),
                         airCompany: "Alitalia",
                         price: 360),
        
        FlightOfferModel(departureCode: "LGA",
                         departureTown: "New York",
                         arrivalCode: "FCO",
                         arrivalTown: "Rome",
                         flightDuration: "9:30",
                         time: "02:00 PM",
                         date: Date(),
                         airCompany: "Delta Airlines",
                         price: 400),
        
        FlightOfferModel(departureCode: "SJJ",
                         departureTown: "Sarajevo",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "1:45",
                         time: "04:00 PM",
                         date: Date(),
                         airCompany: "Lufthansa",
                         price: 180),
        
        FlightOfferModel(departureCode: "FCO",
                         departureTown: "Rome",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "1:20",
                         time: "06:00 AM",
                         date: Date(),
                         airCompany: "Swiss Air",
                         price: 170),
        
        FlightOfferModel(departureCode: "MUC",
                         departureTown: "Munchen",
                         arrivalCode: "LGA",
                         arrivalTown: "New York",
                         flightDuration: "8:55",
                         time: "11:00 AM",
                         date: Date(),
                         airCompany: "Lufthansa",
                         price: 450),
        
        FlightOfferModel(departureCode: "LOS",
                         departureTown: "Lagos",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "7:30",
                         time: "08:00 AM",
                         date: Date(),
                         airCompany: "Swiss Air",
                         price: 500),
        
        FlightOfferModel(departureCode: "LOS",
                         departureTown: "Lagos",
                         arrivalCode: "ZRH",
                         arrivalTown: "Zurich",
                         flightDuration: "7:45",
                         time: "06:00 PM",
                         date: Date(),
                         airCompany: "Ryanair",
                         price: 470)
    ]
}
